### ISSUE TITLE
Deadlock on executing special kind of query

### ISSUE THREAD

**Issue by OlegGalizin** [ClickHouse/clickhouse-cpp#396] opened 2024-09-24 09:32 UTC
I try to write a loader from TVS format.
So i run the query like

   client.Execute("CREATE TEMPORARY TABLE IF NOT EXISTS test_client (id UInt64, name String)");
   client.Execute("insert into test_client FORMAT TSV\n");

and got deadlock in
    client.Execute("insert into test_client FORMAT TSV\n");

The client waits answer from server - the  ServerCodes::EndOfStream code.
The server also waits something. I think it waits some data. What data format is it waiting?
How to send the data that server waiting?

May be it is bug of the clickhouse server.

**Comment by 1261385937** [comment] 2024-09-27 03:27
@OlegGalizin 
It is not a bug.  
client.Execute("insert into test_client FORMAT TSV 1\tClient1\n2\tClient2");

**Comment by 1261385937** [comment] 2024-09-28 09:44
@Enmk @OlegGalizin  Please close it

**Comment by OlegGalizin** [comment] 2024-10-01 12:23
Ok. It is feature with deadlock.

**Closed** 2024-10-01 12:23 UTC
