### ISSUE TITLE
Is Array(LowCardinality(String)) bugged?

### ISSUE THREAD

**Issue by li-darren** [ClickHouse/clickhouse-cpp#163] opened 2022-03-15 13:48 UTC
I was using Array(String) and it seemed to work. I'd create a ColumnString and append all my strings and then in my ColumnArray, I would append as column.

However, with Array(LowCardinality(String)), I would change the database to this type, create a ColumnLowCardinalityT<ColumnString>, append all my values, and then append to the array as a column. This part is fine until I try to insert into my remote db, where I get the error

DB::Exception: Invalid version for DataTypeLowCardinality key column.

**Comment by Enmk** [comment] 2022-04-13 08:18
Closed as a duplicate of: https://github.com/ClickHouse/clickhouse-cpp/issues/163

**Closed by Enmk** 2022-04-13 08:18 UTC
Labels: bug, duplicate

**Comment by li-darren** [comment] 2022-04-13 12:04
duplicate of itself? did you tag the wrong post?
